---
version: 2
plan:
  project-key: AJL
  key: AGTEXTENCODTEST
  name: text-encoding - test
variables:
  dockerPuppeteer: adguard/puppeteer-runner:22.14--24.5--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  docker:
    image: '${bamboo.dockerPuppeteer}'
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # init submodules for tests
            git submodule update --init --recursive

            # Fix mixed logs
            exec 2>&1

            ls -laht

            # Exclude '--ignore-scripts' from pnpm arguments
            # since it prevents postinstall scripts from running
            # so Chrome is not installed which is crucial for tests
            originalPnpmArgs="$bamboo_varsPnpm"
            modifiedPnpmArgs=$(echo "$originalPnpmArgs" | sed 's/--ignore-scripts//g')

            # Install dependencies
            pnpm install ${modifiedPnpmArgs}

            # Run checks
            pnpm test
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules
            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: true

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
